package com.crm.dto;
import lombok.*;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.UUID;
@Data @NoArgsConstructor @AllArgsConstructor @Builder
public class AccountDto {
    private UUID id;
    private String name;
    private String accountNumber;
    private String type;
    private String industry;
    private String subIndustry;
    private String customerStatus;
    private String customerCategory;
    private String segment;
    private String profitCenter;
    private String platform;
    private String subscriptionStatus;
    private String healthscore;
    private String phone;
    private String fax;
    private String website;
    private String accountEmail;
    private String billingStreet;
    private String billingCity;
    private String billingState;
    private String billingPostalCode;
    private String billingCountry;
    private String billingCountryCode;
    private String shippingCity;
    private String shippingCountry;
    private BigDecimal annualRevenue;
    private BigDecimal annualizedRevenue;
    private BigDecimal monthlyRevenue;
    private Integer numberOfEmployees;
    private String numberOfEmployeesRange;
    private String fteSize;
    private String currencyIsoCode;
    private String rating;
    private String accountSource;
    private String ownership;
    private String description;
    private String customerId;
    private String domain;
    private Boolean isActiveSubscription;
    private Boolean churnRisk;
    private UUID ownerId;
    private UUID parentId;
    private UUID clientSuccessManagerId;
    private UUID salesRepresentativeId;
    private OffsetDateTime createdAt;
    private OffsetDateTime updatedAt;
}
