package com.crm.dto;
import lombok.*;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.UUID;
@Data @NoArgsConstructor @AllArgsConstructor @Builder
public class ContractDto {
    private UUID id;
    private String contractNumber;
    private String name;
    private String offerNumber;
    private String legacyId;
    private String description;
    private String specialTerms;
    private String status;
    private String statusCode;
    private Boolean contractActive;
    private String cancellationStatus;
    private String terminationStatus;
    private LocalDate startDate;
    private LocalDate endDate;
    private Integer contractTerm;
    private OffsetDateTime activatedDate;
    private LocalDate companySignedDate;
    private LocalDate customerSignedDate;
    private String customerSignedTitle;
    private LocalDate cancellationDate;
    private LocalDate terminationDate;
    private LocalDate noticePeriodStart;
    private BigDecimal noticePeriodInDays;
    private String accountBookingStatus;
    private String dealType;
    private String industryType;
    private String primaryProduct;
    private String serviceLevel;
    private String originalServiceLevel;
    private String profitCenter;
    private String platform;
    private String clearingHouse;
    private String businessLanguage;
    private BigDecimal annualizedRevenue;
    private BigDecimal monthlyRevenue;
    private BigDecimal newBusinessRevenue;
    private BigDecimal existingBusinessRevenue;
    private BigDecimal totalAmount;
    private BigDecimal remainingBalance;
    private BigDecimal renewalPriceIncreasePct;
    private String currencyIsoCode;
    private String billingFrequency;
    private String billingEmail;
    private String paymentTerms;
    private String paymentStatus;
    private String poNumber;
    private String agreementForm;
    private String billingStreet;
    private String billingCity;
    private String billingState;
    private String billingPostalCode;
    private String billingCountry;
    private String billingCountryCode;
    private String shippingCity;
    private String shippingCountry;
    private BigDecimal seats;
    private BigDecimal totalPurchasedHours;
    private BigDecimal totalRemainingHours;
    private BigDecimal totalPurchasedCredit;
    private BigDecimal totalRemainingCredit;
    private BigDecimal contentViewsLast90;
    private BigDecimal downloadsLast90;
    private BigDecimal activeUsersLast90;
    private String healthscore;
    private String cancellationReason;
    private String terminationReason;
    private String terminationComments;
    private String liableOffice;
    private String userIntegrationStatus;
    private Boolean isAutoRenewal;
    private Boolean isGlobal;
    private Boolean isTrial;
    private Boolean hasConnect;
    private Boolean serviceLevelOverridden;
    private Boolean excludeFromUserSync;
    private BigDecimal openRenewalOpps;
    private BigDecimal closedWonRenewalOpps;
    private BigDecimal numberOfContracts;
    private UUID accountId;
    private String accountName;     // joined from account
    private UUID ownerId;
    private UUID opportunityId;
    private UUID primaryContactId;
    private String primaryContactName;
    private UUID primaryCsManagerId;
    private String primaryCsManagerName;
    private UUID sourceContractId;
    private UUID followUpContractId;
    private UUID pricebook2Id;
    private String salesTeamText;
    private OffsetDateTime createdAt;
    private OffsetDateTime updatedAt;
}
