package com.crm.dto;
import lombok.*;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.UUID;
@Data @NoArgsConstructor @AllArgsConstructor @Builder
public class LeadDto {
    private UUID id;
    private String salutation;
    private String firstName;
    private String lastName;
    private String name;
    private String title;
    private String company;
    private String email;
    private String phone;
    private String mobilePhone;
    private String website;
    private String city;
    private String state;
    private String country;
    private String countryCode;
    private String status;
    private String leadSource;
    private String leadCategory;
    private String rating;
    private String industry;
    private String department;
    private String roleLevel;
    private String platform;
    private String profitCenter;
    private String productOfInterest;
    private String subscriptionStatus;
    private String leadStatusCdp;
    private String unqualifyReason;
    private BigDecimal annualRevenue;
    private Integer numberOfEmployees;
    private String numberOfEmployeesRange;
    private String revenueRange;
    private BigDecimal companyScore;
    private BigDecimal personScore;
    private Boolean converted;
    private LocalDate convertedDate;
    private String nextSteps;
    private Boolean outreachActivelySequenced;
    private String outreachCurrentSequenceName;
    private String outreachCurrentSequenceStatus;
    private Boolean enriched;
    private LocalDate enrichedDate;
    private String domain;
    private OffsetDateTime timestampNew;
    private OffsetDateTime timestampMql;
    private OffsetDateTime timestampQualification;
    private LocalDate lastActivityDate;
    private LocalDate lastMeaningfulConnect;
    private UUID ownerId;
    private String description;
    private OffsetDateTime createdAt;
    private OffsetDateTime updatedAt;
}
