package com.crm.dto;
import lombok.*;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.UUID;
@Data @NoArgsConstructor @AllArgsConstructor @Builder
public class OpportunityDto {
    private UUID id;
    private String name;
    private String description;
    private String type;
    private String accountBookingStatus;
    private String leadSource;
    private String stageName;
    private String forecastCategory;
    private String forecastCategoryName;
    private BigDecimal probability;
    private Integer pushCount;
    private BigDecimal amount;
    private BigDecimal annualRecurringRevenue;
    private BigDecimal monthlyRecurringRevenue;
    private BigDecimal expectedRevenue;
    private BigDecimal newBusinessRevenue;
    private BigDecimal remainingBalance;
    private String currencyIsoCode;
    private BigDecimal renewalPriceIncreasePct;
    private LocalDate closeDate;
    private LocalDate startDate;
    private LocalDate endDate;
    private LocalDate forecastDate;
    private LocalDate quoteValidityDate;
    private LocalDate dateWon;
    private LocalDate lastActivityDate;
    private OffsetDateTime lastStageChangeDate;
    private OffsetDateTime timestampActivation;
    private OffsetDateTime timestampDiscovery;
    private OffsetDateTime timestampNegotiation;
    private OffsetDateTime timestampFinalisation;
    private OffsetDateTime timestampClosed;
    private BigDecimal contractDuration;
    private BigDecimal termInMonths;
    private String autoRenewal;
    private String billingFrequency;
    private String paymentTerms;
    private String poNumber;
    private String agreementForm;
    private String billingEmail;
    private String billingCity;
    private String billingCountryCode;
    private String dealType;
    private String platform;
    private String profitCenter;
    private String primaryProduct;
    private String productOfInterest;
    private String clearingHouse;
    private String renewalSentiment;
    private String approvalStatus;
    private String closingReason;
    private String closingReasonDetail;
    private Boolean won;
    private Boolean closed;
    private Boolean isPrivate;
    private Boolean isAutoRenewal;
    private Boolean isTrial;
    private Boolean isWinBack;
    private Boolean isGlobal;
    private Boolean hasConnectProduct;
    private Boolean discoveryCompleted;
    private Boolean budgetConfirmed;
    private Integer iqScore;
    private String fiscal;
    private Integer fiscalQuarter;
    private Integer fiscalYear;
    private UUID accountId;
    private String accountName;     // joined from account
    private UUID ownerId;
    private UUID primaryContactId;
    private String primaryContactName;
    private UUID clientSuccessManagerId;
    private UUID pricebook2Id;
    private String pricebookName;
    private String salesTeamText;
    private String ownerProfitCenter;
    private String accountCountry;
    private String nextStep;
    private OffsetDateTime createdAt;
    private OffsetDateTime updatedAt;
}
